### ISSUE TITLE
mergeItem doesn't seem to work, Async Storage 1.6.1 RN 0.60.4, Android

### ISSUE THREAD

**Issue by talaikis** [react-native-community/async-storage#175] opened 2019-07-30 18:50 UTC
## Current behavior

mewrgeItem doesn't merge anything, getItem aftermergeItem just either returns old data or null.

## Expected behavior

Should merge new/ updated data, like original package.

## Repro steps

npx react-native init app
npm i -S @react-native-community/async-storage
react-native link @react-native-community/async-storage
const a = { a: 1 }
const b = { a: 2 }
AsyncStorage.setItem('a', JSON.stringify(a))
AsyncStorage.mergetem('a', JSON.stringify(b))
react-native run-android

Better here's repo: https://github.com/talaikis/storage-test

## Environment

- **Async Storage version**: 1.6.1
- **React-Native version**: 0.60.4
- **Platform tested**: Android
- **Logs/Error that are relevant**: No errors, just unpredictable behavior
- **Android build** 28.0.3

**Comment by Krizzu** [comment] 2019-07-30 19:52
@talaikis Try reading from storage after merging.

```javascript
    const a = { a: 1 }
    const b = { a: 2 }

    await AsyncStorage.setItem('a', JSON.stringify(a))
    const oldData = await AsyncStorage.getItem('a')
    console.log({oldData})

    await AsyncStorage.mergeItem('a', JSON.stringify(b))
    const newData = await AsyncStorage.getItem('a')
    console.log({newData})
```

**Comment by talaikis** [comment] 2019-07-30 20:26
> @talaikis Try reading from storage after merging.

Returns null:

```
{ oldData: '{"a":1}' }
{ newData: null }
```

**Comment by Krizzu** [comment] 2019-08-08 20:19
@talaikis 	Do you still seeing this issue? Are you testing this on an emulator or real device?

**Comment by talaikis** [comment] 2019-08-08 21:00
> @talaikis Do you still seeing this issue? Are you testing this on an emulator or real device?

Real deice. I wrote my own JS workaround with getItem, SetItem, etc., because I have very limited time to try to dig into this problem.

**Comment by yazhengwang** [comment] 2019-08-23 12:12
I print AsyncStorage.getItem() read time
2019年8月23日20时5分4秒329毫秒
2019年8月23日20时6分49秒134毫秒

I remember the problem was solved before

**Comment by ingvardm** [comment] 2019-11-12 17:46
reproduces after upgrading to 1.6.2

**Comment by lorenc-tomasz** [comment] 2019-12-12 12:06
The same issue

**Comment by Krizzu** [comment] 2020-04-12 17:01
Please try with latest version (several features/fixes landed). If it's still happening, going to address this.


thanks.

**Closed by Krizzu** 2020-04-12 17:01 UTC
