### ISSUE TITLE
[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

### ISSUE THREAD

**Issue by hms111111** [react-native-community/async-storage#102] opened 2019-05-13 08:14 UTC
in ios pod way,i have try everything....

**Comment by Krizzu** [comment] 2019-05-13 09:08
We need more details to help you.
Please follow issue template and write your configuration, what you tried etc.

**Comment by shuffledex** [comment] 2019-05-13 12:34
maybe it's related: 

```
Loading dependency graph, done.
error: bundling failed: Error: While trying to resolve module `@react-native-community/async-storage` from file `/Users/pj/src/utils/user.js`, the package `/Users/pj/node_modules/@react-native-community/async-storage/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/pj/node_modules/@react-native-community/async-storage/lib/index.js`. Indeed, none of these files exist:
```

"@react-native-community/async-storage": "1.4.0"

**Comment by rafaelbomfim** [comment] 2019-05-13 12:57
with me it does not work either.
I've tried everything.

react-native unlink @react-native-community/async-storage
react-native link @react-native-community/async-storage

pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

pod install

but nothing works on ios

I dont know what to try anymore

**Comment by tido64** [comment] 2019-05-13 16:22
Sorry to hear you have this issue. 😞  Can you try the steps I outlined here and report back: https://github.com/react-native-community/react-native-async-storage/issues/86#issuecomment-489395351

You should make sure that RNCAsyncStorage is a target in the Pods project in Xcode. If it's missing, then CocoaPods haven't linked it in yet, and would explain why you're getting `AsyncStorage is null`. I don't think this is specifically related AsyncStorage.

**Comment by hms111111** [comment] 2019-05-14 01:02
@rafaelbomfim yes,i'm do the same things like you

**Comment by palexs** [comment] 2019-05-27 13:34
In my case I had this issue on Android. The problem was that by default `react-native link` command assumes that `protected List<ReactPackage> getPackages()` method is located in `MainApplication.java`. In our app we moved this method to another file. To solve the issue I had to link manually.

**Comment by infiniteline** [comment] 2019-05-28 17:26
I'm having this issue as well on iOS builds. Not using CocoaPods. Followed @tido64's suggestions from [#86](https://github.com/react-native-community/react-native-async-storage/issues/86#issuecomment-489395351), but to no avail.

**Comment by Krizzu** [comment] 2019-05-28 17:30
Just a reminder: if you're using `Expo` you can't get this package to work.

@infiniteline 	It'd be best if you could provide some more info about your setup/repro steps.


thanks.

**Comment by infiniteline** [comment] 2019-05-28 20:51
Thanks for your reply, @Krizzu. I was able to resolve it for iOS through manual linking. Not sure why I had to resort to that? This is an ejected project that has been made into a workspace after installing Firebase. Do you think that makes a difference?

**Comment by Krizzu** [comment] 2019-05-29 05:33
@infiniteline 	I'm glad you got it working. This could have been due `react native link` nature, where it expects a certain project structure to operate correctly.

**Comment by Vic-L** [comment] 2019-06-03 01:04
I was on a different sheme. Not using the pods ways though. Maybe it may help :)

**Comment by appjitsu** [comment] 2019-06-13 10:03
also using latest expo. cant get this package to work. linking has no effect.

**Comment by Krizzu** [comment] 2019-06-13 13:29
Hi @appjitsu 
[Please checkout troubleshooting docs](https://github.com/react-native-community/async-storage/blob/master/docs/Troubleshooting.md#ios)


thanks.

**Comment by Walaa106** [comment] 2019-06-19 14:15
Manual linking for iOS solved it for me

**Comment by HoangNamVN** [comment] 2019-06-24 04:49
Hello Mr @Krizzu. i have same problem but i already code asyncstorage in my file and i use expo. Can u help me to fix it? i will appreciate it

**Comment by Krizzu** [comment] 2019-06-24 05:45
Hi @HoangNamVN 	

Unfortunately, You cannot use this package with Expo due to its architecture. You can do so by `ejecting` or waiting for Expo team to upgrade to Community's Async Storage.

**Comment by Tyratox** [comment] 2019-06-26 13:19
In that case this should be stated in the README. https://facebook.github.io/react-native/docs/asyncstorage now points to this project.

**Comment by tido64** [comment] 2019-06-26 13:25
To be fair, it is clearly stated in Expo's documentation: https://docs.expo.io/versions/latest/expokit/eject/#should-i-eject-to-expokit. This applies to almost all packages, not just AsyncStorage.

**Comment by Krizzu** [comment] 2019-07-04 14:05
Right, looks like the issue is gone. Closing this one.

**Closed by Krizzu** 2019-07-04 14:05 UTC
Labels: LEGACY

**Comment by msqar** [comment] 2019-07-30 01:30
I'm still having this issue RN 0.60.4 on Android. How can I fix this? Some people say to "manually install it", but how?

**Comment by Krizzu** [comment] 2019-07-30 05:53
@msqar 	We have instructions for [manual linking.](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Linking.md) but the auto-linking feature should do it for you. 

Auto linking should work out of the box if you're willing to dive why it's not happening, checkout [diff comparison between RN 0.59 and 0.60](https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.60.4) to see what changes are necessary to get it to work

**Comment by nolan12345** [comment] 2019-08-24 09:25
问题解决方案
1，react-native unlink @react-native-community/async-storage
2，cd ios && pod install

**Comment by msqar** [comment] 2019-09-17 14:59
@Krizzu yes, as you said... after i properly migrated to 0.60.5 autolinking started to work and everything works as expected, i haven't had to manually install it :) no errors on both Android/iOS. Thanks man!
