### ISSUE TITLE
AsyncStorage not fulfilling promise on Android 7+

### ISSUE THREAD

**Issue by Waqas-Jani** [react-native-community/async-storage#200] opened 2019-08-30 07:51 UTC
Asynstorage not working on android 7+ as i expected.
 try {
            const value = await AsyncStorage.getItem('@history');
            if (value !== null) {
                this.setState({ history: JSON.parse(value) })
            }
        } catch (e) {
            // error reading value
        }
this is the code.. but the promise return nothing..
 it's workig below Anroid 7..
please help me to solve it.. Thanks
## Environment
- **Async Storage version**: 1.6.1
- **React-Native version**: 0.60.4
- **Platform tested**:  Android

**Comment by Krizzu** [comment] 2019-08-30 07:52
@Waqas-Jani 	what do you mean promise return nothing?

**Comment by Waqas-Jani** [comment] 2019-08-30 07:54
empty .. (nothing to show ) in android 7+ 
but working proper below android 7 ..

**Comment by Waqas-Jani** [comment] 2019-08-30 07:56
setItem:
await AsyncStorage.setItem('@history', JSON.stringify(history));
getItem:
 try {
            const value = await AsyncStorage.getItem('@history');
            if (value !== null) {
                this.setState({ history: JSON.parse(value) })
            }
        } catch (e) {
            // error reading value
        }

**Comment by Waqas-Jani** [comment] 2019-08-30 07:59
screen short:: Android 6 
![Screenshot_20190829-162142](https://user-images.githubusercontent.com/38995824/64003521-dcca8880-cb25-11e9-8267-d34c9f79a7c2.png)
Android 7
![1567082263727](https://user-images.githubusercontent.com/38995824/64003605-0388bf00-cb26-11e9-84b7-1da1b3d2519e.JPEG)

**Comment by Waqas-Jani** [comment] 2019-08-30 11:44
Anyone has solution ????

**Comment by Krizzu** [comment] 2019-08-30 13:23
Have you tried to debug/console.log the value you get from `getItem`?

**Comment by Waqas-Jani** [comment] 2019-08-30 18:11
it's release apk file

**Comment by Waqas-Jani** [comment] 2019-09-02 05:19
any solution ???

**Comment by Krizzu** [comment] 2019-09-02 06:19
@Waqas-Jani You'd have to debug it. Run dev build and see what might cause this issue. From your snippet, it seems like you're not handling the situation where `getItems` returns `null` - nothing is saved yet.

**Comment by Waqas-Jani** [comment] 2019-09-02 06:21
it's working on . android 6 ,save data and getting .. but not on android 7.. , not save and get

**Comment by Waqas-Jani** [comment] 2019-09-02 06:22
i checked it . on android 9 and there also not working

**Comment by Waqas-Jani** [comment] 2019-09-02 06:23
in docs. there is nothing to demostration for handling . android version level ..

**Comment by Krizzu** [comment] 2019-09-02 06:47
How about debugging it? Have you checked the logcat output?

**Comment by Waqas-Jani** [comment] 2019-09-02 06:50
yes.. get value in android 6 but not above on android 6. it's null

**Comment by Waqas-Jani** [comment] 2019-09-02 06:50
generate apk file.. same result

**Comment by filiphosko** [comment] 2019-09-02 19:22
@Krizzu I can confirm that this is still happening. I tested it today using GenyMotion - it works well on Android 6 and 8 but fails on Android 7 and 9. Tested it also on "real" devices, Android 6 and 8 and it works. Our client "tested it" today on Android 7 and we had a bug fix to do (really a hack fix, just overriding AsyncStorage on Android 7 and 9, which is not a solution).

**Comment by Krizzu** [comment] 2019-09-02 19:29
@filiphosko So you say you receive `null` every time you call `getItem` on Android 7/9?

Can you do a simple test of saving and then reading a saved value?

**Comment by Waqas-Jani** [comment] 2019-09-03 04:23
@filiphosko  yes it's happening , plz solve it

**Comment by filiphosko** [comment] 2019-09-03 15:33
@Krizzu It didn't return null, it just didn't resolve/reject the promise - no errors. Since we found this problem in the UAT tests, we needed to deploy a quick fix, so we just skipped the calls to AsyncStorage on Nougat and Pie, like this:

```
import {Platform} from 'react-native';

const isDroid = Platform.OS === 'android';
const isNougat = isDroid && (Platform.Version >= 24 && Platform.Version < 26);
const isPie = isDroid && Platform.Version >= 28;

export default function isAsyncStorageSafe() {
  if (isNougat || isPie) {
    return false;
  }

  return true;
}
``` 

This helped immediately  - tested with Genymotion emulator on devices with Nougat and Pie. We deployed the fix and it worked also on the device of our customer (with Nougat installed).

BUT - I tested it today to debug it further, remove the calls to is `isAsyncStorageSafe`... and everything worked. On devices with Nougat and Pie, where it failed yesterday. I checked the commits and really the only difference was that we added this method. So right now I'm clueless, but I'm not confident enough to remove it from the production app.

**Comment by Krizzu** [comment] 2019-09-03 19:42
@filiphosko 	Thanks for your input. Indeed strange case.
Some devs have reported not-resolving promises returning from AsyncStorage. It had to do with shared thread pool Async Storage was using, which on several devices was causing the clog.

Solved it by [adding a dedicated executor feature](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/DedicatedExecutor.md). Maybe this could help.

**Comment by Waqas-Jani** [comment] 2019-09-04 04:33
is it soloved ..??? @Krizzu

**Comment by filiphosko** [comment] 2019-09-04 07:41
@Krizzu thanks for the hint, I'll try it

**Comment by Krizzu** [comment] 2019-09-09 05:54
@filiphosko 	@Waqas-Jani 	did it help?

**Comment by Waqas-Jani** [comment] 2019-09-11 12:28
@filiphosko  i'll try.  thanks for it

**Comment by Krizzu** [comment] 2019-09-23 10:15
@Waqas-Jani any update?

**Comment by Waqas-Jani** [comment] 2019-09-24 07:34
@Krizzu  yet, i don't test on android 7. when i'll test then tell you,

**Comment by Dallas62** [comment] 2019-09-26 17:15
might be same issue as in #219

**Comment by Waqas-Jani** [comment] 2019-10-21 10:44
it's working now. @Krizzu thanks

**Closed** 2020-02-13 22:53 UTC
Labels: LEGACY
