### ISSUE TITLE
AsyncStorage on iOS is buggy

### ISSUE THREAD

**Issue by muhammadn** [react-native-community/async-storage#86] opened 2019-04-18 18:29 UTC
## Current behavior

Using @react-native-community/react-native-async-storage for Android works but for iOS is null when .getItem('@key', value) after .setItem('@key', value)

## Expected behavior

AsyncStorage should get values from .setItem().
I had to revert to use react-native's built-in AsyncStorage in the meantime.

## Repro steps
* Install react-native-community/async-storage:"^1.3.3"
* Launch react-native run ios
* in the code, run await AsyncStorage.setItem('@key', 'value')
* the same code with alert(await AsyncStorage.getItem('@key'))
* value is null

## Environment

- **Async Storage version**: 1.3.3
- **React-Native version**: 0.59.4
- **Platform tested**: iOS and Android
- **Logs/Error that are relevant**:

**Comment by tido64** [comment] 2019-04-18 19:22
Thanks for reporting this, @muhammadn. Your issue seems really odd to me as we have tests in place to prevent complete failures like this. Are you able to repro this in an entirely new app, e.g. in a newly ejected Expo app? Do you see anything in the logs at all?

**Comment by muhammadn** [comment] 2019-04-19 05:18
@tido64 I will try to see the logs in Xcode with a fresh app. I found it is a really nasty bug where i thought it was a problem with my http library that fetches data with tokens stored in AsyncStorage..

I don't use expo though because of CI/CD reasons.

**Comment by raynor85** [comment] 2019-04-19 10:53
@muhammadn It seems to be a bug in the library, and I had the same issue. I have solved it downgrading to v1.2.4, I hope this solves your issue as well.

**Comment by raynor85** [comment] 2019-04-19 11:03
@muhammadn Tip: be sure to omit the caret to guarantee the downgrade. So in your package.json you should have:
```
"@react-native-community/async-storage": "1.2.4",
```
and you should *NOT* have:
```
"@react-native-community/async-storage": "1.2.4",
```
"@react-native-community/async-storage": "^1.2.4",
```

**Comment by muhammadn** [comment] 2019-04-19 11:06
@raynor85  Thanks! 🚀 , so you stick to only 1.2.4 and not upgrade to a patchlevel. Thanks for reminding me of that.  I think i try 1.2.4 after this. Hopefully the bug in the recent release will get fixed soon.

**Comment by tido64** [comment] 2019-04-19 11:09
@raynor85, @muhammadn: Did you also link with the library using `react-native link` or followed the [Linking guide](https://github.com/react-native-community/react-native-async-storage/blob/master/docs/Linking.md)? A bug in 1.2.4 is making your app choose React Native's deprecated AsyncStorage over this library.

**Comment by raynor85** [comment] 2019-04-19 11:11
I did. My podfile has:
```
pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
```

**Comment by tido64** [comment] 2019-04-19 11:15
And you did a `pod install` or `pod update RNCAsyncStorage` afterwards? Sorry for all the questions but I personally learned the hard way that CocoaPods makes a copy of the Pod on install, so you always have to re-run update after a bump. Are you able to set a breakpoint in `RNCAsyncStorage.m` to see if the library gets called at all?

**Comment by muhammadn** [comment] 2019-04-19 11:16
@tido64 I did run react-native link @react-native-community/async-storage. the odd thing was that it runs okay in android but not in ios.

**Comment by tido64** [comment] 2019-04-19 11:19
@muhammadn Link just adds an entry to the `Podfile`. You still need to run `pod install` or `pod update RNCAsyncStorage` afterwards. On Android, link will add an entry to your Gradle build files and will be picked up correctly. CocoaPods is a third party dependency manager, and won't be picked up by Xcode automatically.

**Comment by muhammadn** [comment] 2019-04-19 11:20
@tido64 I will try it out and see if it solves my problem.

**Comment by raynor85** [comment] 2019-04-19 11:21
@tido64 It is installed I confirm that. For me the issue is similar to the one @muhammadn has but it only occurs the first time you try to .setItem('@key', value). When I restart the app, and I execute .setItem('@key', value) again, .getItem('@key', value) will work as expected. I suggest to uninstall the app to try to replicate the bug.

**Comment by muhammadn** [comment] 2019-04-19 11:37
@tido64 weird. i tried to unlink and link again... no `Podfile` file in the ios directory

**Comment by raynor85** [comment] 2019-04-19 11:42
@muhammadn just to clarify, you need to have pod configured in your project, otherwise react-native link will write directly on your project.pbxproj. I suggest you to use the manual guide to install it if you don't have cocoapods installed https://github.com/react-native-community/react-native-async-storage/blob/master/docs/Linking.md#project-linking

**Comment by tido64** [comment] 2019-04-19 11:43
@muhammadn You might have to run `pod init` (see also [Linking](https://github.com/react-native-community/react-native-async-storage/blob/master/docs/Linking.md#using-pods) for the specific steps).

@raynor85 Do you have specific steps to repro this? I tried to repro this in our test app but I can't see it. I manually deleted `RCTAsyncLocalStorage_V1`, and made sure that `setItem` is the very first call:

```bash
$ cat RCTAsyncLocalStorage_V1/manifest.json
{"random":"10"}
```

**Comment by stigi** [comment] 2019-04-23 11:21
@muhammadn Before downgrading or doing anything on a rush can you check if you're actually `await`ing the `setItem` call to finish before calling `getItem`?

**Comment by julianklumpers** [comment] 2019-05-04 12:27
I can confirm i have same issue.
Was using version `1.3.4` and downgraded to version `1.2.4` and everything was working again.

**Comment by Krizzu** [comment] 2019-05-04 15:18
@julianklumpers Do you have any repro steps? What issue you have on v1.3+ ?

**Comment by harkirat1892** [comment] 2019-05-05 03:31
I had just upgraded to 0.59.5 from 0.55.5, and hence migrated to using this library for AsyncStorage, directly to 1.3.4.

Just adding in to help debug the issue, I did not get any issue in the debug or production builds related to AsyncStorage.

**Comment by nvnk3** [comment] 2019-05-05 03:38
I had then same issue with 1.3.3 and 1.3.4.  then I have downgraded to 1.2.4 as mentioned in above comments, then everything works fine for me. we should find the bug.

**Comment by tido64** [comment] 2019-05-05 06:31
This is starting to sound more like a build issue to me. As I mentioned above, 1.2.4 doesn't use this library's native modules. It's equivalent to not using this library at all. Would you mind trying some steps for us?

1. Delete the `node_modules` folder(s) from your project
2. Run `yarn` or `npm install`
3. If you're using CocoaPods:
    1. Make sure your `Podfile` has this entry: `pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'`
    2. Make sure your `Podfile` does _not_ have an entry for `react-native-async-storage`.
    3. `pod install`
    4. `pod update RNCAsyncStorage`
4. Open your Xcode project
5. Press ⇧⌥⌘K to clean your build folder
6. Build and run your project

Let us know how it goes, and please post any suspicious messages in the console that might help us debug this.

**Comment by matjkel** [comment] 2019-05-10 17:48
I was having similar issues. Also using CocoaPods. 

After running `pod update RNCAsyncStorage` the issues were resolved 👍

**Comment by Knjaz89** [comment] 2019-05-13 13:18
same issue
i use 1.4.0

example
```
AsyncStorage.getItem('TEST_KEY', 'TEST_DATA')
        .then((result) => {
            if (result === 'TEST_DATA') {
                console.log(result)
            } else {
                console.log(result)
                AsyncStorage.setItem('TEST_KEY', 'TEST_DATA')
                    .then(() => {
                        console.log('setItem then')
                    })
                    .catch(
                        () => {
                            console.log('setItem catch')
                        }
                    )
            }
        })
        .catch(() => {
            console.log('catch')
        })
```
if I reload my app, getItem return `null`

**Comment by tido64** [comment] 2019-05-13 16:16
@Knjaz89 Can you try the steps I outlined a few posts above?

**Comment by Knjaz89** [comment] 2019-05-14 06:51
> @Knjaz89 Can you try the steps I outlined a few posts above?

yes. i did it. same issue

**Comment by Krizzu** [comment] 2019-05-14 07:00
@Knjaz89 Your example code is wrong - `getItem` does not accept `string` as a second argument.

In your case, there's no app crash (`@RNC/AsyncStorage is null` error), just wrong values saved/read, correct?

**Comment by Knjaz89** [comment] 2019-05-14 08:29
> @Knjaz89 Your example code is wrong - `getItem` does not accept `string` as a second argument.
> 
> In your case, there's no app crash (`@RNC/AsyncStorage is null` error), just wrong values saved/read, correct?

Yep. its my implement. Get item 1 argument.`AsyncStorage.getItem('TEST_KEY')`
does not work

**Comment by Knjaz89** [comment] 2019-05-14 08:32
> @Knjaz89 Your example code is wrong - `getItem` does not accept `string` as a second argument.
> 
> In your case, there's no app crash (`@RNC/AsyncStorage is null` error), just wrong values saved/read, correct?

I set the value, and later request it by hanging the getItem on the button, then everything works.
If you do not make a call by the button, it does not work.

**Comment by Metroninja** [comment] 2019-05-15 10:20
So I've been running up against this issue lately as well, hopefully I can contribute meaningfully.
relevant package.json
```
    "@react-native-community/async-storage": "1.4.0",
    "react": "^16.8.6",
    "react-native": "^0.59.8",
```
podfile:
```
target 'APP-NAME-REMOVED' do
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
```
pod install console log
```
Analyzing dependencies
Fetching podspec for `RNCAsyncStorage` from `../node_modules/@react-native-community/async-storage`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga/yoga.podspec`
Downloading dependencies
Using CocoaLumberjack (3.5.1)
Using RNCAsyncStorage (1.4.0)
Using React (0.59.8)
Using yoga (0.59.8.React)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete!
```
all JS imports (checked countless times)
```
import AsyncStorage from '@react-native-community/async-storage';
```
Of note: my app always shows the yellowbox warning `Warning: Async Storage has been extracted from react-native ...` despite checking every file ad nauseam for importing from the wrong package.  I checked my node_modules to see if it was a dependent package usage, but that doesn't appear to be the case.
My use case:
user logs in to app.
Store auth token in `await AsyncStorage.setItem('@app:auth', token);`
Any other page, during any point after this while the app is live can do a `await AsyncStorage.getItem('@app:auth');` and the token is returned successfully.
As soon as I bounce the app (force close it, dev tool reload) the `await AsyncStorage.getItem('@app:auth');` returns null.

I've been using AsyncStorage in said app without issue for ~1.5 years.  This has only become an issue very, very recently, but I'm not sure if it was when I switched to the community package or if I had seen symptoms before moving to this package.

**Comment by Krizzu** [comment] 2019-05-15 11:15
@Metroninja Hey, thanks, that's very helpful. So it seems like everything is linked/used correctly at your end.

You can see yellow warning probably because of a dependency that still uses `Async Storage` from React Native. 

Do you use `redux-persist` by any chance? Can you repro the same thing with fresh project (more or less your config) ?


thanks.

**Comment by Metroninja** [comment] 2019-05-15 11:16
@Krizzu - I neglected to mention that, which is an important point.  I do not use redux-persist.  I'm currently rolling back async-storage to 1.2.4 to see if that resolves the issue like above, will post shortly my findings.

**Comment by Metroninja** [comment] 2019-05-15 11:20
I can confirm rolling back to version 1.2.4 alleviates the problem  ¯\_(ツ)_/¯

**Comment by Krizzu** [comment] 2019-05-15 12:52
@Metroninja (AFAIR) version 1.2.4 uses `AsyncStorage` from React Native directly, due to regression we found. So it's not really solving any issue.

If you remove `RNC Async Storage` do you still see yellow warning?

**Comment by Metroninja** [comment] 2019-05-15 13:02
@Krizzu I don't want to sidetrack the issue with the yellowbox warning (as so often happens in github issues), I want to do my best to assist in tracking down the iOS persisting it's data issue!  That said next when I fire up a debug build later I'll check.

as to v 1.2.4, the value for me was to see if the old package (since it was mentioned above that it used the old library directly) was the issue, or if there truly is a problem with the new library, and it appears there is something wrong here to cause this.  It seems like asyncStorage is working just fine until the app reloads, after which time the data is dropped by the iOS app.

**Comment by Krizzu** [comment] 2019-05-15 14:54
@Metroninja Right, thanks for help so far. I want to eliminate other possible causes. It'd be great to have a repo that can reflect the issue you're having. I launched Example and created a new project from `init` - `AsyncStorage` works fine for me, holding data after reload/app restart. Any idea how to reproduce your case?

thanks

**Comment by Metroninja** [comment] 2019-05-16 12:03
I've spun up a small test project and have yet to reproduce the bug.  I'm going to see what other factors here could cause it, if I can track down a direct repro I'll upload the repo here.  Next areas I plan to look are with redux and/or react-navigation.

**Comment by HeffZilla** [comment] 2019-05-20 18:40
> This is starting to sound more like a build issue to me. As I mentioned above, 1.2.4 doesn't use this library's native modules. It's equivalent to not using this library at all. Would you mind trying some steps for us?
> 
> 1. Delete the `node_modules` folder(s) from your project
> 2. Run `yarn` or `npm install`
> 3. If you're using CocoaPods:
>    
>    1. Make sure your `Podfile` has this entry: `pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'`
>    2. Make sure your `Podfile` does _not_ have an entry for `react-native-async-storage`.
>    3. `pod install`
>    4. `pod update RNCAsyncStorage`
> 4. Open your Xcode project
> 5. Press ⇧⌥⌘K to clean your build folder
> 6. Build and run your project
> 
> Let us know how it goes, and please post any suspicious messages in the console that might help us debug this.

This really helped me. Now running Async Storage (community) v1.4.0.

**Comment by franzwarning** [comment] 2019-05-22 10:35
Running 1.2.4 fixes the issue for us. Will this issue be addressed in future releases? Pretty serious bug imo.

**Comment by MalikHezretov** [comment] 2019-05-22 10:57
Hi @Krizzu, I face same issue as @raynor85 also I use redux-persist. I get null value first time from AsyncStorage.getItem() when I reload the app then I get the actual value. I use AsyncStorage directly from react-native 57.8 inside App.js. Were you able to to get it work for you?

**Comment by kbateman** [comment] 2019-05-22 11:22
using 1.3.4 and 1.4.0 (and using react native debugger to log whats written to asyncstorage)

Not seeing keys being written to async storage with above versions. Without restarting app at all.

using 1.2.4 seeing keys written to asyncstorage correctly (assuming this is because its actually using the internal react-native asyncstorage because of the 1.2.4 regression issue)

**Comment by MalikHezretov** [comment] 2019-05-23 05:32
@Krizzu thanks for replying.

I get null instead of expected value first time. Then if I restart the app and go to that page second time I get the expected value.

**Comment by Krizzu** [comment] 2019-05-23 05:51
@MalikHezretov right, could it be there some kind of race to save data? You can try to debug `AsyncStorage` which you have in `node_modules` (by putting, console logs in `getItem/setItem` methods, to see what's happening.

**Comment by MalikHezretov** [comment] 2019-05-23 05:55
@Krizzu I believe data is being saved it is there in storage but The the problem is getting that item. I will debug it and see to be sure. Thanks.

**Comment by MalikHezretov** [comment] 2019-05-23 05:58
@Krizzu The weird thing is, same code works fine on Android and not on iOS for first time only.

**Comment by IvarsAkmentins** [comment] 2019-05-25 19:23
Hi, 
I also have this issue. On loading I get error message "[@RNC/AsyncStorage]:NativeModule: AsyncStorage is null." And in code I only have "import AsyncStorage from '@react-native-community/async-storage';".

 I have tried cleaning packager cache, removing node module and installing again. unlinking and linking.

dependencies:
`"dependencies": {
    "@expo/samples": "2.1.1",
    "@react-native-community/async-storage": "1.4.1",
    "aws-amplify": "^1.1.27",
    "aws-amplify-react-native": "^2.1.11",
    "expo": "^32.0.0",
    "lodash.isequal": "^4.5.0",
    "native-base": "^2.12.1",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-button": "^2.4.0",
    "react-native-elements": "^1.1.0",
    "react-navigation": "^3.10.2",
    "reactotron-react-native": "^3.5.2"
  }`

**Comment by StefanBuchman** [comment] 2019-06-18 10:12
Running into the same issue on my side.  After updating from 1.2.4 to 1.5.0 (or 1.4.x) I can add an item and read it immediately but a reload of the app or even running `showAsyncStorageContentInDev()` in the debugger will show the items were never persisted to storage.

I've tried re-installing, linking, unlinking but nothing seems to work.  I've also manually linked but doesn't work either.  Downgraded to 1.2.4 for now as that's the only version that seems to work.

**Comment by Krizzu** [comment] 2019-06-18 11:34
Hey @StefanBuchman 

[Please check out my comment about this issue here](https://github.com/react-native-community/async-storage/issues/118#issuecomment-500138053).


thanks.

**Comment by Krizzu** [comment] 2019-07-04 14:14
Closing down - [please refer to my comment on the issue here ](https://github.com/react-native-community/async-storage/issues/118#issuecomment-500138053).


thanks.

**Closed by Krizzu** 2019-07-04 14:14 UTC
Labels: Bug, LEGACY, Platform: iOS

**Comment by bmp123** [comment] 2019-08-12 08:02
@react-native-community/async-storage v1.6.1 same issue on ios, v1.2.4 work perfect

**Comment by zhangjunhou** [comment] 2019-09-10 12:07
Overtime is to blame

**Comment by robleds** [comment] 2019-10-29 03:22
> @muhammadn Tip: be sure to omit the caret to guarantee the downgrade. So in your package.json you should have:
> 
> ```
> "@react-native-community/async-storage": "1.2.4",
> ```
> 
> and you should _NOT_ have:
> 
> ```
> "@react-native-community/async-storage": "^1.2.4",
> ```

works like a charm !

**Comment by Krizzu** [comment] 2019-10-29 06:25
@robleds Using `1.2.4` is like using `AsyncStorage` from `react-native`.

For iOS issue: I'd double check if one of your dependencies is still using AS from core - if it's the case, that means there's a race condition between Community's version and the core one. 

If you're able to, change dependencies to use Community's `AsyncStorage`, otherwise, better fall back to `react-native`

**Comment by ammarRajabA** [comment] 2019-11-15 08:09
Why 1.2.4 is working and latest version is buggy .. I'm using latest version and it acts weird on iOS (Android is fine). An error for example appeared sometimes `“RCTAsyncLocalStorage_V1” couldn’t be removed.`when I wanna clear the storage

This error sometimes appears and sometimes not which is strange.

I used this solution 

```
const asyncStorageKeys = await AsyncStorage.getAllKeys();
if (asyncStorageKeys.length > 0) {
  AsyncStorage.clear();
}
```

**Comment by Dylan0916** [comment] 2020-03-10 04:14
any update?

**Comment by Flouwrian** [comment] 2020-04-09 13:34
I also would be interested, still encountering the IOS problem in 1.7.4

**Comment by Benzer1406** [comment] 2020-04-29 00:17
Have the same issue in 1.9.0

**Comment by Krizzu** [comment] 2020-04-29 07:38
Please describe what you issue you have in bit more details.

**Comment by perdona** [comment] 2020-09-03 04:03
this should not be closed. ran into it on sep/20
when trying to clear asyncStorage, on iOS simulator, I'm getting the error above.
using this snippet to clear
```
AsyncStorage.clear().then(() => {
        setLoggedUser(null);
});
