### ISSUE TITLE
E/ReactNativeJS: Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

### ISSUE THREAD

**Issue by jameerjbr** [react-native-community/async-storage#273] opened 2020-01-03 17:33 UTC
## Current behavior

IOS is correctly working but android is not working

## Environment

- **Async Storage version**:     "@react-native-community/async-storage": "^1.7.1",
   
- **React-Native version**:  "react-native": "0.61.5",
- **Platform tested**:  Android

**Comment by gochinj** [comment] 2020-01-04 22:05
+1 Except iOS is failing, have not tried Android yet.

**Comment by diegoaraujolima** [comment] 2020-01-07 18:49
+ 1 Android.

AsyncStorage 1.7,1
ReactNative 0.61.4

**Comment by Krizzu** [comment] 2020-01-08 13:56
I'd need more details - what's not working?

**Comment by diegoaraujolima** [comment] 2020-01-08 14:13
When starting the application the error E / ReactNativeJS: Error: [@ RNC / AsyncStorage]: NativeModule: AsyncStorage is null.

**Comment by Krizzu** [comment] 2020-01-08 20:16
@diegoaraujolima This error comes from the not properly installed native module. RN 60+ is using autolinking, so you don't have to do nothing more, but follow the Autolinking setup. Otherwise, you need to use `react-native link` to install it.

**Comment by diegoaraujolima** [comment] 2020-01-09 03:48
My version is 0.61.4 and I didn't use the link and the problem occurs. Then I tried to rotate the link, but the error still remains. Then I tried to do the operations manually (change MainApplication, dependencies and etc) and the error keeps occurring.

**Comment by Krizzu** [comment] 2020-01-09 07:56
If you have upgraded from <0.60 version, [you can use update helper to see what changes you need to make on android part to make autolinking work](https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.61.4)

**Comment by diegoaraujolima** [comment] 2020-01-09 13:55
But I am not migrating from version. I just installed the latest version.

**Comment by JKshared92** [comment] 2020-01-09 14:33
I also encountered this problem

**Comment by RunningShadow-007** [comment] 2020-01-10 10:14
I met the same issue
---
IOS is correctly working but android is not working
---
- Async Storage version: "@react-native-community/async-storage": "^1.7.1",

- React-Native version: "react-native": "0.57.8",

- Platform tested: Android

**Comment by Krizzu** [comment] 2020-01-12 19:37
If you upgraded from < 0.60 version, you need to unlink all your dependencies and then relay just on [cli feature](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md). Please read the docs to get more info.

If you started with version 0.60+, then autolinking should kick in. no `react-native link` is required. You just need to make sure that the setup you have follows the proper setup. Again, [here are the docs for autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md).

If you're below version 0.60, then you have to install the dependency manually or through `react-native link name-of-the-library`. [We have guides for manual linking here](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Linking.md)

**Comment by StoyanD** [comment] 2020-01-15 20:12
I had the same problem, looks like auto-linking is broken on android:
# Environment

- Async Storage version: "@react-native-community/async-storage": "^1.7.1",
- React-Native version: "react-native": "0.61.5",
- Platform tested: Android

# Fix
In order to fix it I had to manually modify my `Applications.kt` file. 

```
              import com.reactnativecommunity.asyncstorage.AsyncStoragePackage
              import com.swmansion.gesturehandler.react.RNGestureHandlerPackage
```

and then make sure you add the packages to the `getPackages()` return list:

```
              override fun getPackages(): List<ReactPackage> =
                           listOf(
                                      MainReactPackage(),
                                      RNGestureHandlerPackage(),
                                      AsyncStoragePackage()
                           )
```

The fix should be similar if you are using java instead of kotlin.

**Comment by Krizzu** [comment] 2020-01-16 09:05
@StoyanD AFAIK, auto-linking does not work with Kotlin (yet?)
cc @thymikee

**Comment by thymikee** [comment] 2020-01-16 09:08
Should work just fine, if you import PackageList correctly, @dratwas did some work on that. Code from @StoyanD looks like pre-autolinking, see https://github.com/facebook/react-native/blob/0.61-stable/template/android/app/src/main/java/com/helloworld/MainApplication.java#L25 for reference.

**Comment by jessegranger** [comment] 2020-02-18 16:18
Same issue.  Latest Expo, running on Android.

Steps to Reproduce
--------------------------
Start with a clean blank-template project.

Add:
```
AsyncStorage = require('@react-native-community/async-storage)
```

Start the project with `yarn start`, load the project with Expo on Android.

Instant crash.

The above references to Java code are not helpful, I'm not writing any Java/Kotlin at all in this pipeline.

**Comment by Krizzu** [comment] 2020-02-18 18:18
@jessegranger Expo does not support custom native modules, so you cannot add Async Storage to.

**Comment by jessegranger** [comment] 2020-02-20 00:40
Thanks for your answer. I did `expo eject` and then `react-native link ...` and it worked in Android emulator.

**Comment by Krizzu** [comment] 2020-02-24 07:14
Closing it down - for any other cases, please open new issue.

**Closed by Krizzu** 2020-02-24 07:14 UTC
Labels: LEGACY
